---
# Download nextcloud version, unpack to specified directory, create configuration file
- name: "Create data directory"
  file:
    path: "{{ nextcloud_data_directory }}"
    mode: "u=rwX,g=rX,o-rwx"
    recurse: True
    state: directory
    owner: "{{ nextcloud_owner }}"
    group: "{{ nextcloud_group }}"

- name: "Allow changes to install directory"
  file:
    path: "{{ nextcloud_directory }}"
    state: directory
    recurse: True
    owner: "{{ nextcloud_owner }}"
    group: "{{ nextcloud_group }}"

- name: "Warn if password was not changed"
  pause:
    prompt: "nextcloud_admin_password is 'nextcloud', make sure to change this after installation! Press enter to confirm"
  when:
    - nextcloud_admin_password == 'nextcloud'

- block:
  - name: "Ensure no config.php is present"
    file:
      path: "{{ nextcloud_configuration }}"
      state: absent

  - name: "Install nextcloudu using OCC command"
    become_user: "{{ nextcloud_owner }}"
    become_flags: "{{ ansible_become_flags | default(omit) }}"
    become: yes
    command: >
        php occ maintenance:install
        --database={{ nextcloud_database.type }}
        --database-host={{ nextcloud_database.hostname }}
        --database-port={{ nextcloud_database.port }}
        --database-name={{ nextcloud_database.name }}
        --database-user={{ nextcloud_database.username }}
        --database-pass={{ nextcloud_database.password }}
        --admin-user={{ nextcloud_admin_user }}
        --admin-pass={{ nextcloud_admin_password }}
        --data-dir={{ nextcloud_data_directory }}
    args:
      chdir: "{{ nextcloud_directory }}"
      creates: "{{ nextcloud_configuration }}"
    notify: reload http

  - name: "Check config.php is not empty"
    stat:
      path: "{{ nextcloud_configuration }}"
    register: nextcloud_config_size
    failed_when: nextcloud_config_size.stat.size is undefined or nextcloud_config_size.stat.size <= 100

  - name: "Verify php syntax"
    command: "php -l {{ nextcloud_configuration }}"
    register: nextcloud_config_validate
    changed_when: False
    failed_when:
      - nextcloud_config_validate.rc is defined
      - nextcloud_config_validate.rc != 0

  rescue:
    - name: "Cleanup if installation failed"
      file:
        path: "{{ nextcloud_configuration }}"
        state: absent
      failed_when: True