---
# tasks file for peschmae.nextcloud
- name: Check if PHP exists
  ansible.builtin.command: "{{ nextcloud_php_executable }} -v"
  register: nextcloud_check_php
  failed_when: nextcloud_check_php.rc != 0
  changed_when: false

- name: Check config.php is not empty
  ansible.builtin.stat:
    path: "{{ nextcloud_configuration }}"
  register: nextcloud_config_file
  changed_when: false

- import_tasks: download.yml
  when: "'isreg' not in nextcloud_config_file.stat"

- import_tasks: install.yml
  when: "'isreg' not in nextcloud_config_file.stat"

- import_tasks: configuration.yml

- include_tasks: applications.yml
  with_items: "{{ nextcloud_apps }}"
