---
- name: Converge
  hosts: nextcloud
  vars:
    nextcloud_admin_password: molecule
    nextcloud_php_executable: /opt/bitnami/php/bin/php
    nextcloud_database_hostname: mysql
    nextcloud_apps:
      - name: breezedark
        enabled: True
        config:
          theme_enabled: "1"
          theme_login_page: "1"
      - name: drawio
        enabled: False
    nextcloud_cronjob_additional:
      - name: nextcloud_groupfolder-scan
        enabled: true
        command: "{{ nextcloud_php_executable }} {{ nextcloud_directory }}/occ groupfolders:scan 1"
        schedule: "*/5 * * * *"
  tasks:
    - name: "Include peschmae.nextcloud"
      ansible.builtin.include_role:
        name: "peschmae.nextcloud"
