FROM bitnami/php-fpm

RUN apt update && \
    apt install -y python3 sudo cron logrotate && \
    # debugging only...
    # apt install -y netcat iputils-ping dnsutils && \
    # to install php-redis through pecl
    apt install -y build-essential libtool autoconf unzip wget && \
    apt clean