FROM bitnami/php-fpm

RUN apt update && \
    apt install -y python3 sudo cron && \
    # debugging only...
    # apt install -y netcat iputils-ping dnsutils && \
    apt clean && \
    echo "memory_limit 512M" > /opt/bitnami/php/etc/conf.d/memory.ini