---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: mysql
    image: mysql:debian
    pre_build_image: true
    env:
      MYSQL_ROOT_PASSWORD: molecule
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    exposed_ports:
      - 3306/tcp
    network_mode: bridge
    docker_networks:
      - name: nextcloud
    networks:
      - name: nextcloud
    override_command: False
  - name: redis
    image: redis:alpine
    pre_build_image: true
    exposed_ports:
      - 6379/tcp
    network_mode: bridge
    docker_networks:
      - name: nextcloud
    networks:
      - name: nextcloud
    override_command: False
  - name: nextcloud
    image: "bitnami/php-fpm"
    pre_build_image: false
    network_mode: bridge
    networks:
      - name: nextcloud
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    prepare: ../default/prepare.yml
verifier:
  name: ansible