---
- name: Install requirements
  hosts: nextcloud
  tasks:
    - name: create www-data group
      ansible.builtin.group:
        name: www-data
        gid: 33

    - name: create www-data user
      ansible.builtin.user:
        name: www-data
        uid: 33
        group: www-data

    - name: increase memory limit
      ansible.builtin.copy:
        content: "memory_limit = 512M"
        dest: /opt/bitnami/php/etc/conf.d/memory.ini
        owner: 1000
        group: 1000
        mode: 0644

    - name: enable apcu
      ansible.builtin.copy:
        content: "extension = apcu.so"
        dest: /opt/bitnami/php/etc/conf.d/apcu.ini
        owner: 1000
        group: 1000
        mode: 0644

    - name: install php-redis through pecl
      ansible.builtin.command: "yes no | pecl install redis"

    - name: enable redis
      ansible.builtin.copy:
        content: "extension = redis.so"
        dest: /opt/bitnami/php/etc/conf.d/redis.ini
        owner: 1000
        group: 1000
        mode: 0644

    - name: list enabled php modules
      ansible.builtin.command: "php -m"
      register: debug_enabled_php_modules

    - name: show enabled php modules
      debug:
        var: debug_enabled_php_modules.stdout