---
- name: Converge
  hosts: nextcloud
  vars:
    nextcloud_admin_password: molecule
    nextcloud_php_executable: /opt/bitnami/php/bin/php
    nextcloud_database_hostname: mysql
  tasks:
    - name: "Include peschmae.nextcloud"
      ansible.builtin.include_role:
        name: "peschmae.nextcloud"
