---
- name: Converge
  hosts: nextcloud
  vars:
    nextcloud_admin_password: molecule
    nextcloud_php_executable: /opt/bitnami/php/bin/php
    nextcloud_database:
      type: mysql
      name: nextcloud
      hostname: mysql
      port: 3306
      username: nextcloud
      password: nextcloud
    nextcloud_apps:
      - name: breezedark
        enabled: True
        config:
          theme_enabled: "1"
          theme_login_page: "1"
      - name: drawio
        enabled: True
  tasks:
    - name: "Include peschmae.nextcloud"
      include_role:
        name: "peschmae.nextcloud"
